"""
Wiki writer — generates and maintains wiki pages from research outputs.

The wiki is a markdown knowledge base at D:/CODEX/Omnigent/wiki/.
Structure:
  wiki/
    index.md          — Master index of all pages
    log.md            — Chronological log of research activities
    SCHEMA.md         — Page schema/template definitions
    raw/              — Raw extracted content from researchers
    {topic}.md        — Per-topic research pages
"""

import os
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Any, Optional


WIKI_ROOT = Path("D:/CODEX/Omnigent/wiki")
RAW_DIR = WIKI_ROOT / "raw"
INDEX_PATH = WIKI_ROOT / "index.md"
LOG_PATH = WIKI_ROOT / "log.md"
SCHEMA_PATH = WIKI_ROOT / "SCHEMA.md"


class WikiWriter:
    """Manages wiki page creation and updates."""
    
    def __init__(self, wiki_root: Optional[Path] = None):
        self.wiki_root = wiki_root or WIKI_ROOT
        self.raw_dir = self.wiki_root / "raw"
        self._ensure_dirs()
    
    def _ensure_dirs(self):
        """Create wiki directory structure if it doesn't exist."""
        self.wiki_root.mkdir(parents=True, exist_ok=True)
        self.raw_dir.mkdir(parents=True, exist_ok=True)
        
        # Create index if it doesn't exist
        if not INDEX_PATH.exists():
            INDEX_PATH.write_text("# Omnigent Wiki Index\n\n*Auto-generated by the orchestration pipeline*\n\n## Pages\n")
        
        # Create log if it doesn't exist
        if not LOG_PATH.exists():
            LOG_PATH.write_text("# Research Log\n\n*Auto-generated by the orchestration pipeline*\n")
        
        # Create schema if it doesn't exist
        if not SCHEMA_PATH.exists():
            SCHEMA_PATH.write_text("""# Wiki Page Schema

## Survey Template
```
# {Topic}

## Overview
## Theoretical Foundations
## Key Architectures
## State of the Art
## Implementations
## Benchmarks
## Applications
## Open Questions
## References
```

## Comparison Template
```
# {Item A} vs {Item B}

## Overview
## Architecture Comparison
## Performance Comparison
## Tradeoffs
## When to Use Which
## References
```

## Implementation Template
```
# {Paper} Implementation

## Paper Summary
## Core Algorithm
## Implementation Details
## Code Structure
## Tests
## Benchmarks
## References
```
""")
    
    def create_page(self, name: str, content: str, template: str = "survey") -> Path:
        """Create or overwrite a wiki page."""
        page_path = self.wiki_root / f"{name}.md"
        timestamp = datetime.now().isoformat()
        
        header = f"<!-- Generated by Omnigent Orchestrator at {timestamp} -->\n"
        header += f"<!-- Template: {template} -->\n\n"
        
        page_path.write_text(header + content)
        self._update_index(name, template)
        self._append_log(f"Created page: {name} (template: {template})")
        
        return page_path
    
    def append_to_page(self, name: str, section: str, content: str):
        """Append content to a specific section of a wiki page."""
        page_path = self.wiki_root / f"{name}.md"
        
        if not page_path.exists():
            self.create_page(name, f"## {section}\n\n{content}")
            return
        
        existing = page_path.read_text()
        
        # Try to find the section header
        section_header = f"## {section}"
        if section_header in existing:
            # Insert after the section header
            parts = existing.split(section_header, 1)
            new_content = parts[0] + section_header + "\n\n" + content + "\n" + parts[1]
        else:
            # Append as new section
            new_content = existing.rstrip() + f"\n\n{section_header}\n\n{content}\n"
        
        page_path.write_text(new_content)
        self._append_log(f"Updated page: {name} (section: {section})")
    
    def save_raw(self, task_id: str, filename: str, content: str) -> Path:
        """Save raw extracted content."""
        raw_path = self.raw_dir / task_id
        raw_path.mkdir(exist_ok=True)
        file_path = raw_path / filename
        file_path.write_text(content)
        return file_path
    
    def get_page(self, name: str) -> Optional[str]:
        """Read a wiki page."""
        page_path = self.wiki_root / f"{name}.md"
        if page_path.exists():
            return page_path.read_text()
        return None
    
    def list_pages(self) -> List[str]:
        """List all wiki pages."""
        pages = []
        for f in self.wiki_root.glob("*.md"):
            if f.name not in ("index.md", "log.md", "SCHEMA.md"):
                pages.append(f.stem)
        return sorted(pages)
    
    def _update_index(self, name: str, template: str):
        """Update the wiki index with a new page entry."""
        index_text = INDEX_PATH.read_text()
        entry = f"- [{name}]({name}.md) — `{template}` — {datetime.now().strftime('%Y-%m-%d')}"
        
        if name not in index_text:
            # Add to Pages section
            lines = index_text.split("\n")
            new_lines = []
            in_pages = False
            added = False
            for line in lines:
                new_lines.append(line)
                if line.strip() == "## Pages":
                    in_pages = True
                elif in_pages and not added and line.startswith("- "):
                    # Insert alphabetically
                    if name < line[2:].split("]")[0].split("(")[0]:
                        new_lines.insert(-1, entry)
                        added = True
                elif in_pages and not added and (line.startswith("##") or line == ""):
                    if line.startswith("##") and line != "## Pages":
                        new_lines.insert(-1, entry)
                        added = True
            if not added:
                new_lines.append(entry)
            
            INDEX_PATH.write_text("\n".join(new_lines))
    
    def _append_log(self, message: str):
        """Append an entry to the research log."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        log_entry = f"\n### {timestamp}\n{message}\n"
        
        with open(LOG_PATH, "a") as f:
            f.write(log_entry)
